ds_course = [['Advanced Data Mining with Weka MOOC', 'https://www.cs.waikato.ac.nz/ml/weka/mooc/advanceddataminingwithweka/'],
            ['An Introduction to Data Science', 'https://www.udemy.com/course/an-introduction-to-data-science/'],
            ['Applied Data Science with Python', 'https://cognitiveclass.ai/learn/data-science-with-python'],
            ['CS250: Python for Data Science', 'https://learn.saylor.org/course/view.php?id=504'],
            ['Data Analysis and Visualization', 'https://www.udacity.com/course/data-analysis-and-visualization--ud404'],
            ['Data Analysis with Python: Zero to Pandas', 'https://jovian.ai/learn/data-analysis-with-python-zero-to-pandas'],
            ['Data Analysis with R', 'https://www.udacity.com/course/data-analysis-with-r--ud651'],
            ['Data Build Tool (dbt)', 'https://www.youtube.com/playlist?list=PLy4OcwImJzBLJzLYxpxaPUmCWp8j1esvT'],
            ['Data Cleaning', 'https://www.kaggle.com/learn/data-cleaning'],
            ['Data Engineering', 'https://www.youtube.com/playlist?list=PLy4OcwImJzBKg3rmROyI_CBBAYlQISkOO'],
            ['Data Mining with Weka MOOC', 'https://www.cs.waikato.ac.nz/ml/weka/mooc/dataminingwithweka/'],
            ['Data science for beginners', 'https://microsoft.github.io/Data-Science-For-Beginners'],
            ['Data Science Fundamentals', 'https://cognitiveclass.ai/learn/data-science'],
            ['Data Science interview questions', 'https://www.youtube.com/playlist?list=PLZoTAELRMXVPkl7oRvzyNnyj1HS4wt2K-'],
            ['Data Science Methodology', 'https://cognitiveclass.ai/courses/data-science-methodology-2'],
            ['Data Visualization', 'https://www.kaggle.com/learn/data-visualization'],
            ['Datavis 2020', 'https://www.youtube.com/playlist?list=PL9yYRbwpkykuK6LSMLH3bAaPpXaDUXcLV'],
            ['Hadoop Tutorial for Beginners', 'https://www.youtube.com/playlist?list=PLlgLmuG_KgbasW0lpInSAIxYd2vqAEPit'],
            ['Hive Tutorial', 'https://www.youtube.com/watch?v=MLDcapDQba4'],
            ['IBM Data Science Professional Certificate', 'https://www.coursera.org/professional-certificates/ibm-data-science'],
            ['Intro to Data Analysis', 'https://www.udacity.com/course/intro-to-data-analysis--ud170'],
            ['Intro to Data Science', 'https://www.udacity.com/course/intro-to-data-science--ud359'],
            ['Introduction to Data Science', 'https://alison.com/course/introduction-to-data-science-revised'],
            ['Introduction to Data Science in Python', 'https://www.coursera.org/learn/python-data-analysis'],
            ['Learn Data Science', 'https://www.sololearn.com/learning/1093'],
            ['Learn Data Science Tutorial - Full Course for Beginners', 'https://www.youtube.com/watch?v=ua-CiDNNj30'],
            ['Machine Learning', 'https://www.udacity.com/course/machine-learning--ud262'],
            ['More Data Mining with Weka MOOC', 'https://www.cs.waikato.ac.nz/ml/weka/mooc/moredataminingwithweka/'],
            ['NICO 101 - Introduction to Programming for Big Data', 'https://github.com/amarallab/Amaral_Lab_Intro_to_Data_Science'],
            ['The Analytics Edge', 'https://www.edx.org/course/analytics-edge-mitx-15-071x-3']]

web_course = [['ASP.NET Core Tutorial For Beginners', 'https://www.youtube.com/playlist?list=PL6n9fhu94yhVkdrusLaQsfERmL_Jh4XmU'],
            ['Command Line Power User - for web developers', 'https://commandlinepoweruser.com'],
            ['Create a Professional Website with Velo by Wix', 'https://www.codecademy.com/learn/create-a-professional-website-with-velo-by-wix'],
            ['CS50’s Web Programming with Python and JavaScript', 'https://cs50.harvard.edu/web/'],
            ['Developing for Web Accessibility', 'https://www.w3.org/WAI/tips/developing/'],
            ['Discover Flask - Full Stack Web Development with Flask', 'https://github.com/realpython/discover-flask'],
            ['Essential Nextjs Typescript Tailwind Stack', 'https://www.youtube.com/playlist?list=PLKEkvhqFCRwL94nLP-TdIfNmbiZk5FCMx'],
            ['Flask(A Python Microframework) Tutorial', 'http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world'],
            ['Foundations of Front End Web Development', 'https://www.udemy.com/course/foundations-of-front-end-development/'],
            ['Frontend UI Development with React', 'https://www.youtube.com/playlist?list=PL0vfts4VzfNgUUEtEjxDVfh4iocVR3qIb']]

android_course = [['Android Development for Beginners [Free]','https://youtu.be/fis26HvvDII'],
                  ['Android App Development Specialization','https://www.coursera.org/specializations/android-app-development'],
                  ['Associate Android Developer Certification','https://grow.google/androiddev/#?modal_active=none'],
                  ['Become an Android Kotlin Developer by Udacity','https://www.udacity.com/course/android-kotlin-developer-nanodegree--nd940'],
                  ['Android Basics by Google','https://www.udacity.com/course/android-basics-nanodegree-by-google--nd803'],
                  ['The Complete Android Developer Course','https://www.udemy.com/course/complete-android-n-developer-course/'],
                  ['Building an Android App with Architecture Components','https://www.linkedin.com/learning/building-an-android-app-with-architecture-components'],
                  ['Android App Development Masterclass using Kotlin','https://www.udemy.com/course/android-oreo-kotlin-app-masterclass/'],
                  ['Flutter & Dart - The Complete Flutter App Development Course','https://www.udemy.com/course/flutter-dart-the-complete-flutter-app-development-course/'],
                  ['Flutter App Development Course [Free]','https://youtu.be/rZLR5olMR64']]

ios_course = [['IOS App Development by LinkedIn','https://www.linkedin.com/learning/subscription/topics/ios'],
              ['iOS & Swift - The Complete iOS App Development Bootcamp','https://www.udemy.com/course/ios-13-app-development-bootcamp/'],
              ['Become an iOS Developer','https://www.udacity.com/course/ios-developer-nanodegree--nd003'],
              ['iOS App Development with Swift Specialization','https://www.coursera.org/specializations/app-development'],
              ['Mobile App Development with Swift','https://www.edx.org/professional-certificate/curtinx-mobile-app-development-with-swift'],
              ['Swift Course by LinkedIn','https://www.linkedin.com/learning/subscription/topics/swift-2'],
              ['Objective-C Crash Course for Swift Developers','https://www.udemy.com/course/objectivec/'],
              ['Learn Swift by Codecademy','https://www.codecademy.com/learn/learn-swift'],
              ['Swift Tutorial - Full Course for Beginners [Free]','https://youtu.be/comQ1-x2a1Q'],
              ['Learn Swift Fast - [Free]','https://youtu.be/FcsY1YPBwzQ']]

uiux_course = [['Complete Guide to UI/UX Design', 'https://www.udemy.com/course/complete-guide-to-ux-ui-design/'],
            ['User Interface Design Specialization', 'https://www.coursera.org/specializations/user-interface-design'],
            ['UI/UX Design & Prototyping using Adobe XD', 'https://www.udemy.com/course/uiux-web-design-using-adobe-xd/'],
            ['UX Design: From Concept to Prototype', 'https://www.coursera.org/learn/ux-design-concept-prototype'],
            ['Mobile UX Design Fundamentals', 'https://www.udacity.com/course/mobile-ux-design-fundamentals--ud849'],
            ['Creating a Perfect UX Portfolio', 'https://www.linkedin.com/learning/creating-a-perfect-ux-portfolio'],
            ['UX Design for Mobile Developers', 'https://www.udacity.com/course/ux-design-for-mobile-developers--ud849'],
            ['Learn Figma - UI/UX Design Essential Training', 'https://www.udemy.com/course/learn-figma/'],
            ['Sketch from A to Z: Become an App Designer', 'https://www.udemy.com/course/sketch-design/'],
            ['Principles of Design', 'https://www.coursera.org/learn/design-principles']]

resume_videos = [ 'https://youtu.be/Tt08KmFfIYQ','https://youtu.be/y8YH0Qbu5h4',
                  'https://youtu.be/u75hUSShvnc','https://youtu.be/BYUy1yvjHxE',
                  'https://youtu.be/KFaugkGVeNQ','https://youtu.be/3agP4x8LYFM',
                  'https://youtu.be/GyjzOKdaioU','https://youtu.be/17YZBH_qtmg',
                  'https://youtu.be/C7pNLIq3kOI','https://youtu.be/xpaz7nrNmXA',
                  'https://youtu.be/aKjsy-b00QM','https://youtu.be/ciIkiWwZnlc']

interview_videos = ['https://youtu.be/HG68Ymazo18','https://youtu.be/BOvAAoxM4vg',
                    'https://youtu.be/KukmClH1KoA','https://youtu.be/7_aAicmPB3A',
                    'https://youtu.be/1mHjMNZZvFo','https://youtu.be/WfdtKbAJOmE',
                    'https://youtu.be/IBjM-F56qS0','https://youtu.be/IBjM-F56qS0',
                    'https://youtu.be/4tYoVx0QoN0','https://youtu.be/Ge0Udbws1kc',
                    'https://youtu.be/thkuu_FWFD8','https://youtu.be/e0E6-dRPcJA',
                    'https://youtu.be/htT1bhFSNxo','https://youtu.be/TZ3C_syg9Ow']
